// Code generated by Icestudio 0.7.1w202110170310

`default_nettype none

//---- Top entity
module main #(
 parameter va62210 = 0,
 parameter v39d6c3 = 30000,
 parameter v59c048 = 240000-1,
 parameter v270d90 = 6000,
 parameter v31e2cf = 0,
 parameter vb8fe3c = 240000-1,
 parameter v0dbfe4 = 0,
 parameter vb2a722 = 30000,
 parameter vbfa6c8 = 240000-1,
 parameter v5564e5 = 6000,
 parameter v739f8a = 0,
 parameter v39aedd = 240000-1,
 parameter v3e9ba6 = 0,
 parameter v2c81fe = 30000,
 parameter ve5c988 = 240000-1,
 parameter v861a57 = 0,
 parameter v2174a9 = 6000,
 parameter ve03a08 = 240000-1,
 parameter vfd19d2 = 18000,
 parameter v791626 = 13635,
 parameter v96ace2 = 6000,
 parameter vf6a2c6 = 240000-1
) (
 input v86c0ae,
 input v66b8d3,
 input v49e008,
 input v308b59,
 input v5d0570,
 input vb8e6e0,
 input vclk,
 output v1e49f0,
 output v32ad9b,
 output vacba4d,
 output va6efd8,
 output [0:7] vinit
);
 localparam p1 = vfd19d2;
 localparam p4 = v96ace2;
 localparam p5 = vf6a2c6;
 localparam p11 = v791626;
 localparam p18 = v861a57;
 localparam p22 = v2174a9;
 localparam p23 = ve03a08;
 localparam p27 = v3e9ba6;
 localparam p31 = v2c81fe;
 localparam p33 = ve5c988;
 localparam p39 = v0dbfe4;
 localparam p42 = vb2a722;
 localparam p43 = vbfa6c8;
 localparam p47 = v5564e5;
 localparam p49 = v739f8a;
 localparam p53 = v39aedd;
 localparam p62 = va62210;
 localparam p65 = v39d6c3;
 localparam p66 = v59c048;
 localparam p70 = v270d90;
 localparam p73 = v31e2cf;
 localparam p77 = vb8fe3c;
 wire w0;
 wire [0:19] w2;
 wire [0:19] w3;
 wire [0:19] w6;
 wire [0:19] w7;
 wire w8;
 wire [0:19] w9;
 wire w10;
 wire [0:15] w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire [0:19] w19;
 wire w20;
 wire [0:19] w21;
 wire [0:19] w24;
 wire [0:19] w25;
 wire w26;
 wire [0:19] w28;
 wire w29;
 wire [0:19] w30;
 wire [0:19] w32;
 wire [0:19] w34;
 wire [0:19] w35;
 wire [0:19] w36;
 wire w37;
 wire w38;
 wire [0:19] w40;
 wire [0:19] w41;
 wire [0:19] w44;
 wire [0:19] w45;
 wire [0:19] w46;
 wire w48;
 wire [0:19] w50;
 wire w51;
 wire [0:19] w52;
 wire [0:19] w54;
 wire [0:19] w55;
 wire [0:19] w56;
 wire w57;
 wire w58;
 wire w59;
 wire w60;
 wire w61;
 wire [0:19] w63;
 wire [0:19] w64;
 wire [0:19] w67;
 wire [0:19] w68;
 wire [0:19] w69;
 wire w71;
 wire w72;
 wire [0:19] w74;
 wire w75;
 wire [0:19] w76;
 wire [0:19] w78;
 wire [0:19] w79;
 wire [0:19] w80;
 wire w81;
 wire w82;
 wire w83;
 wire w84;
 wire w85;
 wire w86;
 wire w87;
 wire w88;
 wire w89;
 wire w90;
 wire w91;
 wire w92;
 wire w93;
 wire w94;
 wire w95;
 wire w96;
 wire w97;
 wire w98;
 wire w99;
 wire w100;
 assign w0 = v86c0ae;
 assign v1e49f0 = w8;
 assign v32ad9b = w14;
 assign w16 = v66b8d3;
 assign w17 = v49e008;
 assign w26 = v308b59;
 assign w48 = v5d0570;
 assign vacba4d = w60;
 assign va6efd8 = w61;
 assign w72 = vb8e6e0;
 assign w87 = vclk;
 assign w88 = vclk;
 assign w89 = vclk;
 assign w90 = vclk;
 assign w91 = vclk;
 assign w92 = vclk;
 assign w93 = vclk;
 assign w94 = vclk;
 assign w95 = vclk;
 assign w96 = vclk;
 assign w97 = vclk;
 assign w98 = vclk;
 assign w99 = vclk;
 assign w100 = vclk;
 assign w58 = w57;
 assign w59 = w51;
 assign w75 = w71;
 assign w88 = w87;
 assign w89 = w87;
 assign w89 = w88;
 assign w90 = w87;
 assign w90 = w88;
 assign w90 = w89;
 assign w91 = w87;
 assign w91 = w88;
 assign w91 = w89;
 assign w91 = w90;
 assign w92 = w87;
 assign w92 = w88;
 assign w92 = w89;
 assign w92 = w90;
 assign w92 = w91;
 assign w93 = w87;
 assign w93 = w88;
 assign w93 = w89;
 assign w93 = w90;
 assign w93 = w91;
 assign w93 = w92;
 assign w94 = w87;
 assign w94 = w88;
 assign w94 = w89;
 assign w94 = w90;
 assign w94 = w91;
 assign w94 = w92;
 assign w94 = w93;
 assign w95 = w87;
 assign w95 = w88;
 assign w95 = w89;
 assign w95 = w90;
 assign w95 = w91;
 assign w95 = w92;
 assign w95 = w93;
 assign w95 = w94;
 assign w96 = w87;
 assign w96 = w88;
 assign w96 = w89;
 assign w96 = w90;
 assign w96 = w91;
 assign w96 = w92;
 assign w96 = w93;
 assign w96 = w94;
 assign w96 = w95;
 assign w97 = w87;
 assign w97 = w88;
 assign w97 = w89;
 assign w97 = w90;
 assign w97 = w91;
 assign w97 = w92;
 assign w97 = w93;
 assign w97 = w94;
 assign w97 = w95;
 assign w97 = w96;
 assign w98 = w87;
 assign w98 = w88;
 assign w98 = w89;
 assign w98 = w90;
 assign w98 = w91;
 assign w98 = w92;
 assign w98 = w93;
 assign w98 = w94;
 assign w98 = w95;
 assign w98 = w96;
 assign w98 = w97;
 assign w99 = w87;
 assign w99 = w88;
 assign w99 = w89;
 assign w99 = w90;
 assign w99 = w91;
 assign w99 = w92;
 assign w99 = w93;
 assign w99 = w94;
 assign w99 = w95;
 assign w99 = w96;
 assign w99 = w97;
 assign w99 = w98;
 assign w100 = w87;
 assign w100 = w88;
 assign w100 = w89;
 assign w100 = w90;
 assign w100 = w91;
 assign w100 = w92;
 assign w100 = w93;
 assign w100 = w94;
 assign w100 = w95;
 assign w100 = w96;
 assign w100 = w97;
 assign w100 = w98;
 assign w100 = w99;
 v888484 v58e191 (
  .vd9601b(w0),
  .v157a67(w10),
  .vfde3d7(w87)
 );
 v95d0ae #(
  .vc5c8ea(p1)
 ) va5476c (
  .v2531bd(w2)
 );
 vbe214f v2438c0 (
  .va1de2f(w2),
  .v2c450d(w3),
  .v3f443e(w9),
  .v2d3366(w10)
 );
 v95d0ae #(
  .vc5c8ea(p4)
 ) v08503b (
  .v2531bd(w3)
 );
 v95d0ae #(
  .vc5c8ea(p5)
 ) v2eeddc (
  .v2531bd(w6)
 );
 v82aaa0 v33aba7 (
  .vb2cfec(w6),
  .vb319d4(w7),
  .v6dda25(w88)
 );
 v1bc657 v7854fa (
  .v0e4f6c(w7),
  .v4642b6(w8),
  .v0a4fd8(w9)
 );
 v651fa3 #(
  .vc5c8ea(p11)
 ) v777eb3 (
  .vcd9338(w12)
 );
 v58b797 v4a7eba (
  .v2dc030(w12),
  .ve37344(w13),
  .v6dda25(w89)
 );
 vbef3fc vbbc490 (
  .v3dc29f(w13),
  .v4642b6(w15),
  .v6dda25(w90)
 );
 v7ebc90 vf14f77 (
  .vcbab45(w14),
  .v0e28cb(w15),
  .v3ca442(w16)
 );
 v888484 v7319a1 (
  .vd9601b(w17),
  .v157a67(w20),
  .vfde3d7(w91)
 );
 v95d0ae #(
  .vc5c8ea(p18)
 ) vafb44e (
  .v2531bd(w19)
 );
 vbe214f v86670c (
  .va1de2f(w19),
  .v2d3366(w20),
  .v2c450d(w21),
  .v3f443e(w32)
 );
 v95d0ae #(
  .vc5c8ea(p22)
 ) vd68d8d (
  .v2531bd(w21)
 );
 v95d0ae #(
  .vc5c8ea(p23)
 ) va1747a (
  .v2531bd(w24)
 );
 v82aaa0 vaf67cd (
  .vb2cfec(w24),
  .vb319d4(w25),
  .v6dda25(w92)
 );
 v1bc657 v979376 (
  .v0e4f6c(w25),
  .v0a4fd8(w32),
  .v4642b6(w37)
 );
 v888484 v03630a (
  .vd9601b(w26),
  .v157a67(w29),
  .vfde3d7(w93)
 );
 v95d0ae #(
  .vc5c8ea(p27)
 ) v6d512f (
  .v2531bd(w28)
 );
 vbe214f v4de776 (
  .va1de2f(w28),
  .v2d3366(w29),
  .v2c450d(w30),
  .v3f443e(w36)
 );
 v95d0ae #(
  .vc5c8ea(p31)
 ) v9b114c (
  .v2531bd(w30)
 );
 v528969 vc320f0 (
  .v483980(w37),
  .vb7d864(w38),
  .vb5d757(w57)
 );
 v95d0ae #(
  .vc5c8ea(p33)
 ) v9273d3 (
  .v2531bd(w34)
 );
 v82aaa0 vd34f8b (
  .vb2cfec(w34),
  .vb319d4(w35),
  .v6dda25(w94)
 );
 v1bc657 va0de79 (
  .v0e4f6c(w35),
  .v0a4fd8(w36),
  .v4642b6(w38)
 );
 v95d0ae #(
  .vc5c8ea(p39)
 ) v5dec4b (
  .v2531bd(w40)
 );
 vbe214f vc91314 (
  .va1de2f(w40),
  .v2c450d(w41),
  .v3f443e(w46),
  .v2d3366(w59)
 );
 v95d0ae #(
  .vc5c8ea(p42)
 ) vd1b1c4 (
  .v2531bd(w41)
 );
 v95d0ae #(
  .vc5c8ea(p43)
 ) v3497c3 (
  .v2531bd(w44)
 );
 v82aaa0 va0c3c4 (
  .vb2cfec(w44),
  .vb319d4(w45),
  .v6dda25(w95)
 );
 v1bc657 v6dff97 (
  .v0e4f6c(w45),
  .v0a4fd8(w46),
  .v4642b6(w82)
 );
 v95d0ae #(
  .vc5c8ea(p47)
 ) vf723d4 (
  .v2531bd(w52)
 );
 v888484 vfec378 (
  .vd9601b(w48),
  .v157a67(w51),
  .vfde3d7(w96)
 );
 v95d0ae #(
  .vc5c8ea(p49)
 ) vcc1235 (
  .v2531bd(w50)
 );
 vbe214f v73f195 (
  .va1de2f(w50),
  .v2d3366(w51),
  .v2c450d(w52),
  .v3f443e(w56)
 );
 v95d0ae #(
  .vc5c8ea(p53)
 ) v341d39 (
  .v2531bd(w54)
 );
 v82aaa0 v5963de (
  .vb2cfec(w54),
  .vb319d4(w55),
  .v6dda25(w97)
 );
 v1bc657 vb04d4d (
  .v0e4f6c(w55),
  .v0a4fd8(w56),
  .v4642b6(w84)
 );
 v528969 v2002ce (
  .v483980(w58),
  .vb5d757(w60),
  .vb7d864(w85)
 );
 v528969 v71efdc (
  .v483980(w57),
  .vb5d757(w61),
  .vb7d864(w86)
 );
 v528969 v53a996 (
  .vb7d864(w81),
  .v483980(w82),
  .vb5d757(w85)
 );
 v95d0ae #(
  .vc5c8ea(p62)
 ) v37ff85 (
  .v2531bd(w63)
 );
 vbe214f v53312b (
  .va1de2f(w63),
  .v2c450d(w64),
  .v3f443e(w69),
  .v2d3366(w71)
 );
 v95d0ae #(
  .vc5c8ea(p65)
 ) v716beb (
  .v2531bd(w64)
 );
 v95d0ae #(
  .vc5c8ea(p66)
 ) v602cc6 (
  .v2531bd(w67)
 );
 v82aaa0 v2cfb97 (
  .vb2cfec(w67),
  .vb319d4(w68),
  .v6dda25(w98)
 );
 v1bc657 v965958 (
  .v0e4f6c(w68),
  .v0a4fd8(w69),
  .v4642b6(w83)
 );
 v95d0ae #(
  .vc5c8ea(p70)
 ) v23e8a2 (
  .v2531bd(w76)
 );
 v888484 v8efd0b (
  .v157a67(w71),
  .vd9601b(w72),
  .vfde3d7(w99)
 );
 v95d0ae #(
  .vc5c8ea(p73)
 ) va0964c (
  .v2531bd(w74)
 );
 vbe214f v816254 (
  .va1de2f(w74),
  .v2d3366(w75),
  .v2c450d(w76),
  .v3f443e(w80)
 );
 v95d0ae #(
  .vc5c8ea(p77)
 ) v24fb2a (
  .v2531bd(w78)
 );
 v82aaa0 va7d02b (
  .vb2cfec(w78),
  .vb319d4(w79),
  .v6dda25(w100)
 );
 v1bc657 vbb320a (
  .v0e4f6c(w79),
  .v0a4fd8(w80),
  .v4642b6(w81)
 );
 v528969 ve22877 (
  .vb7d864(w83),
  .v483980(w84),
  .vb5d757(w86)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v888484 #(
 parameter v9d2d5b = 0,
 parameter v42e61f = 0
) (
 input vfde3d7,
 input vd9601b,
 output v157a67,
 output v64879c
);
 localparam p4 = v9d2d5b;
 localparam p5 = v42e61f;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w6;
 wire w7;
 assign w0 = vd9601b;
 assign v157a67 = w1;
 assign v64879c = w3;
 assign w6 = vfde3d7;
 assign w7 = vfde3d7;
 assign w2 = w1;
 assign w7 = w6;
 v31e84e v9cfc0f (
  .ve78ab8(w2),
  .v3487af(w3),
  .ved8395(w7)
 );
 v0b641d #(
  .v17ea21(p4),
  .v803182(p5)
 ) v6ca512 (
  .v27dec4(w0),
  .v4642b6(w1),
  .v25ab12(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Button-tic  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Button-tic: Configurable button that emits a tic when it is pressed
/*-------------------------------------------------*/
//---- Top entity
module v31e84e (
 input ved8395,
 input ve78ab8,
 output v3487af
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = ve78ab8;
 assign w1 = ved8395;
 assign w4 = ve78ab8;
 assign v3487af = w5;
 assign w4 = w0;
 v053dc2 v1bde40 (
  .vf54559(w0),
  .va4102a(w1),
  .ve8318d(w2)
 );
 v3676a0 v9d4cda (
  .v0e28cb(w2),
  .vcbab45(w3)
 );
 vba518e v57aa83 (
  .v0e28cb(w3),
  .v3ca442(w4),
  .vcbab45(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Rising-edge-detector  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Rising-edge detector. It generates a 1-period pulse (tic) when a rising edge is detected on the input
/*-------------------------------------------------*/
//---- Top entity
module v053dc2 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v053dc2_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- D Flip-flop (verilog implementation)
/*-------------------------------------------------*/

module v053dc2_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg q = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOT gate (Verilog implementation)
/*-------------------------------------------------*/

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Two bits input And gate
/*-------------------------------------------------*/

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v0b641d #(
 parameter v17ea21 = 0,
 parameter v803182 = 0
) (
 input v25ab12,
 input v27dec4,
 output v4642b6
);
 localparam p2 = v803182;
 localparam p4 = v17ea21;
 wire w0;
 wire w1;
 wire w3;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v25ab12;
 assign w8 = v25ab12;
 assign w8 = w7;
 v6c3aff #(
  .v2fb6e5(p4)
 ) v67ee04 (
  .v758f58(w0),
  .vedbc89(w6)
 );
 vf718a5 v5e6bb3 (
  .v6a82dd(w3),
  .vd4e5d7(w5),
  .v444878(w8)
 );
 vdc93d6 v71ab2a (
  .ve7f5e6(w0),
  .v3c12b5(w1),
  .v717e81(w7)
 );
 vad96dc #(
  .v6a9fe4(p2)
 ) vc0a9e9 (
  .v27dec4(w1),
  .v4642b6(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Button  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Configurable button (pull-up on/off. Not on/off)
/*-------------------------------------------------*/
//---- Top entity
module v6c3aff #(
 parameter v2fb6e5 = 1
) (
 input vedbc89,
 output v758f58
);
 localparam p2 = v2fb6e5;
 wire w0;
 wire w1;
 assign w0 = vedbc89;
 assign v758f58 = w1;
 v6c3aff_v34955f #(
  .ON(p2)
 ) v34955f (
  .i(w0),
  .o(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Pull-upx1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- FPGA internal pull-up configuration on the input port
/*-------------------------------------------------*/

module v6c3aff_v34955f #(
 parameter ON = 0
) (
 input i,
 output o
);
 // 1-Pull up
 
 //-- Place the IO block, configured as  
 //-- input with pull-up
 SB_IO
   #(
     .PIN_TYPE(6'b 1010_01),
     
     //-- The pull-up is activated or not
     //-- depeding on the ON parameter
     .PULLUP(ON)
     
   ) input_pin (
 
     //--- Input pin
     .PACKAGE_PIN(i),
     
     //-- Block output
     .D_IN_0(o),
     
     //-- Configured as input
     .OUTPUT_ENABLE(1'b0),
     
     //-- Not used
     .D_OUT_0(1'b0)
   );
endmodule
//---- Top entity
module vf718a5 (
 input v444878,
 input v6a82dd,
 output vd4e5d7
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign w2 = v444878;
 assign w3 = v444878;
 assign w4 = v444878;
 assign vd4e5d7 = w5;
 assign w6 = v6a82dd;
 assign w7 = v6a82dd;
 assign w3 = w2;
 assign w4 = w2;
 assign w4 = w3;
 assign w7 = w6;
 v93adf6 ve5d8ab (
  .v9afc1f(w0),
  .va4102a(w2),
  .ve8318d(w5),
  .vf54559(w6)
 );
 v413e4a v93d042 (
  .ve37344(w0),
  .ve556f1(w1),
  .v6dda25(w3)
 );
 v332488 vf5eed3 (
  .v3487af(w1),
  .ved8395(w4),
  .ve78ab8(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- Debouncer-x01  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Remove the rebound on a mechanical switch
/*-------------------------------------------------*/
//---- Top entity
module v93adf6 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 input v9afc1f,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 wire w4;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 assign w4 = v9afc1f;
 v93adf6_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3),
  .load(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Reg-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 1bit register (implemented in verilog)
/*-------------------------------------------------*/

module v93adf6_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 input load,
 output q
);
 reg q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module v413e4a (
 input v6dda25,
 input ve556f1,
 output [15:0] v49911e,
 output ve37344
);
 wire w0;
 wire [0:15] w1;
 wire [0:15] w2;
 wire w3;
 wire [0:15] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v49911e = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 vbc711b v8fa00b (
  .v782748(w0),
  .v3f90b8(w1),
  .vc320da(w2),
  .v6dda25(w3)
 );
 v8ecd59 v9392cd (
  .v2f9d57(w1),
  .vd7988b(w2),
  .v4642b6(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- syscounter-rst-16bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 16-bits Syscounter with reset
/*-------------------------------------------------*/
//---- Top entity
module vbc711b (
 input v6dda25,
 input v782748,
 input [15:0] vc320da,
 output [15:0] v3f90b8
);
 wire [0:15] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w0 = vc320da;
 assign v3f90b8 = w1;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 v5c75f6 vbdef88 (
  .v4de61b(w2),
  .v50034e(w6),
  .v6dda25(w13),
  .v782748(w17)
 );
 v5c75f6 v6188f9 (
  .v4de61b(w3),
  .v50034e(w7),
  .v6dda25(w12),
  .v782748(w16)
 );
 v852bc8 vd47660 (
  .v91b9c1(w0),
  .v527ffb(w2),
  .v71a717(w3),
  .v0b337e(w4),
  .vfc89f9(w5)
 );
 v401a28 v3ef916 (
  .v14a530(w1),
  .vcc76e8(w6),
  .vd531e6(w7),
  .v7ef7d6(w8),
  .v1447f2(w9)
 );
 v5c75f6 v9f7443 (
  .v4de61b(w4),
  .v50034e(w8),
  .v6dda25(w11),
  .v782748(w15)
 );
 v5c75f6 vd2d6b6 (
  .v4de61b(w5),
  .v50034e(w9),
  .v6dda25(w10),
  .v782748(w14)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF-rst-x16  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- DFF-rst-x16: 16 D flip-flops in paralell with reset
/*-------------------------------------------------*/
//---- Top entity
module v5c75f6 (
 input v6dda25,
 input v782748,
 input [3:0] v4de61b,
 output [3:0] v50034e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w6 = v4de61b;
 assign v50034e = w7;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 vc4f23a v4b1225 (
  .v3f8943(w2),
  .v64d863(w3),
  .vda577d(w4),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v6491fd (
  .v03aaf0(w0),
  .vee8a83(w1),
  .vf8041d(w5),
  .v11bca5(w7),
  .vd84a57(w9)
 );
 v2be0f8 v10a04f (
  .v4642b6(w0),
  .vf354ee(w3),
  .vd53b77(w13),
  .v27dec4(w17)
 );
 v2be0f8 v7d9648 (
  .v4642b6(w1),
  .vf354ee(w2),
  .vd53b77(w12),
  .v27dec4(w16)
 );
 v2be0f8 v004b14 (
  .vf354ee(w4),
  .v4642b6(w5),
  .vd53b77(w11),
  .v27dec4(w15)
 );
 v2be0f8 v8aa818 (
  .vf354ee(w8),
  .v4642b6(w9),
  .vd53b77(w10),
  .v27dec4(w14)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF-rst-x04  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- DFF-rst-x04: Three D flip-flops in paralell with reset
/*-------------------------------------------------*/
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus4-Split-all  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus4-Split-all: Split the 4-bits bus into its wires
/*-------------------------------------------------*/

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus4-Join-all  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus4-Join-all: Join all the wires into a 4-bits Bus
/*-------------------------------------------------*/

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v2be0f8 #(
 parameter vbd3217 = 0
) (
 input vd53b77,
 input v27dec4,
 input vf354ee,
 output v4642b6
);
 localparam p5 = vbd3217;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 assign w2 = v27dec4;
 assign w3 = vf354ee;
 assign v4642b6 = w4;
 assign w6 = vd53b77;
 v3676a0 v7539bf (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 vba518e vfe8158 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v053dc2 #(
  .v71e305(p5)
 ) vd104a4 (
  .vf54559(w0),
  .ve8318d(w4),
  .va4102a(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF-rst-x01  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- DFF-rst-x01: D Flip flop with reset input. When rst=1, the DFF is 0
/*-------------------------------------------------*/
//---- Top entity
module v852bc8 (
 input [15:0] v91b9c1,
 output [3:0] vfc89f9,
 output [3:0] v0b337e,
 output [3:0] v71a717,
 output [3:0] v527ffb
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign w0 = v91b9c1;
 assign v527ffb = w1;
 assign v71a717 = w2;
 assign v0b337e = w3;
 assign vfc89f9 = w4;
 v852bc8_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus16-Split-quarter  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus16-Split-quarter: Split the 16-bits bus into four buses of the same size
/*-------------------------------------------------*/

module v852bc8_v9a2a06 (
 input [15:0] i,
 output [3:0] o3,
 output [3:0] o2,
 output [3:0] o1,
 output [3:0] o0
);
 assign o3 = i[15:12];
 assign o2 = i[11:8];
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v401a28 (
 input [3:0] v1447f2,
 input [3:0] v7ef7d6,
 input [3:0] vd531e6,
 input [3:0] vcc76e8,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign v14a530 = w0;
 assign w1 = vcc76e8;
 assign w2 = vd531e6;
 assign w3 = v7ef7d6;
 assign w4 = v1447f2;
 v401a28_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus16-Join-quarter  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus16-Join-quarter: Join the four same buses into an 16-bits Bus
/*-------------------------------------------------*/

module v401a28_v9a2a06 (
 input [3:0] i3,
 input [3:0] i2,
 input [3:0] i1,
 input [3:0] i0,
 output [15:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v8ecd59 #(
 parameter v6c5139 = 1
) (
 input [15:0] v2f9d57,
 output v4642b6,
 output [15:0] vd7988b
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:15] w2;
 wire [0:15] w3;
 assign v4642b6 = w0;
 assign w2 = v2f9d57;
 assign vd7988b = w3;
 v265696 #(
  .vd73390(p1)
 ) v76123a (
  .v4642b6(w0),
  .v36f2dd(w2),
  .vc068fb(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Inc1-16bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Inc1-16bit: Increment a 16-bits number by one
/*-------------------------------------------------*/
//---- Top entity
module v265696 #(
 parameter vd73390 = 0
) (
 input [15:0] v36f2dd,
 output v4642b6,
 output [15:0] vc068fb
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:15] w2;
 wire [0:15] w3;
 wire [0:15] w4;
 assign v4642b6 = w0;
 assign w3 = v36f2dd;
 assign vc068fb = w4;
 v651fa3 #(
  .vc5c8ea(p1)
 ) vdd8fa2 (
  .vcd9338(w2)
 );
 vbc66d7 vce7ab7 (
  .v4642b6(w0),
  .v1489e0(w2),
  .v603a9a(w3),
  .v2c4251(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderK-16bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderK-16bit: Adder of 16-bit operand and 16-bit constant
/*-------------------------------------------------*/
//---- Top entity
module v651fa3 #(
 parameter vc5c8ea = 0
) (
 output [15:0] vcd9338
);
 localparam p0 = vc5c8ea;
 wire [0:15] w1;
 assign vcd9338 = w1;
 v651fa3_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 16-bits-gen-constant  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Generic: 16-bits generic constant
/*-------------------------------------------------*/

module v651fa3_v465065 #(
 parameter VALUE = 0
) (
 output [15:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vbc66d7 (
 input [15:0] v1489e0,
 input [15:0] v603a9a,
 output v4642b6,
 output [15:0] v2c4251
);
 wire w0;
 wire w1;
 wire [0:15] w2;
 wire [0:15] w3;
 wire [0:15] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 assign v4642b6 = w0;
 assign w2 = v603a9a;
 assign w3 = v1489e0;
 assign v2c4251 = w4;
 v306ca3 v0a29fe (
  .v91b9c1(w2),
  .vef5eee(w9),
  .vd3ef3b(w10)
 );
 v306ca3 vb0a6ce (
  .v91b9c1(w3),
  .vef5eee(w7),
  .vd3ef3b(w8)
 );
 vcb23aa v8e0bba (
  .v4642b6(w1),
  .v62bf25(w6),
  .v39966a(w8),
  .veb2f59(w10)
 );
 vc3c498 v917bbf (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .veeaa8e(w5),
  .v45c6ee(w7),
  .v20212e(w9)
 );
 v8cc49c v03c3e3 (
  .v14a530(w4),
  .vb334ae(w5),
  .v2b8a97(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-16bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-16bits: Adder of two operands of 16 bits
/*-------------------------------------------------*/
//---- Top entity
module v306ca3 (
 input [15:0] v91b9c1,
 output [7:0] vef5eee,
 output [7:0] vd3ef3b
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v91b9c1;
 assign vef5eee = w1;
 assign vd3ef3b = w2;
 v306ca3_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus16-Split-half  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus16-Split-half: Split the 16-bits bus into two buses of the same size
/*-------------------------------------------------*/

module v306ca3_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vcb23aa (
 input [7:0] v39966a,
 input [7:0] veb2f59,
 output v4642b6,
 output [7:0] v62bf25
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 assign w0 = veb2f59;
 assign w1 = v39966a;
 assign v62bf25 = w4;
 assign v4642b6 = w5;
 v6bdcd9 vd88c66 (
  .vcc8c7c(w0),
  .v651522(w9),
  .v2cc41f(w10)
 );
 v6bdcd9 v26a0bb (
  .vcc8c7c(w1),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v25966b v9ea427 (
  .v817794(w3),
  .v4642b6(w6),
  .v0550b6(w8),
  .v24708e(w10)
 );
 vafb28f vc75346 (
  .v515fe7(w2),
  .v3c88fc(w3),
  .va9ac17(w4)
 );
 va1ce30 v40c17f (
  .v817794(w2),
  .v4642b6(w5),
  .vb9cfc3(w6),
  .v0550b6(w7),
  .v24708e(w9)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-8bits: Adder of two operands of 8 bits
/*-------------------------------------------------*/
//---- Top entity
module v6bdcd9 (
 input [7:0] vcc8c7c,
 output [3:0] v651522,
 output [3:0] v2cc41f
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign v651522 = w0;
 assign v2cc41f = w1;
 assign w2 = vcc8c7c;
 v6bdcd9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus8-Split-half  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus8-Split-half: Split the 8-bits bus into two buses of the same size
/*-------------------------------------------------*/

module v6bdcd9_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v25966b (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w14),
  .v82de4f(w17)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w12),
  .v82de4f(w16)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w13),
  .vda577d(w16),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w11),
  .vda577d(w12),
  .v3f8943(w14),
  .v64d863(w15)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w11),
  .v82de4f(w13)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-4bits: Adder of two operands of 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-1bit: Adder of two operands of 1 bit
/*-------------------------------------------------*/
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderC-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
/*-------------------------------------------------*/
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- XOR2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- XOR gate: two bits input xor gate
/*-------------------------------------------------*/

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR2: Two bits input OR gate
/*-------------------------------------------------*/

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- bit-0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Constant bit 0
/*-------------------------------------------------*/

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module vafb28f (
 input [3:0] v515fe7,
 input [3:0] v3c88fc,
 output [7:0] va9ac17
);
 wire [0:7] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign va9ac17 = w0;
 assign w1 = v515fe7;
 assign w2 = v3c88fc;
 vafb28f_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus8-Join-half  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus8-Join-half: Join the two same halves into an 8-bits Bus
/*-------------------------------------------------*/

module vafb28f_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module va1ce30 (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 input vb9cfc3,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 assign w11 = vb9cfc3;
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w13),
  .v82de4f(w17)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w14),
  .vda577d(w17),
  .v3f8943(w18),
  .v64d863(w19)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w12),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w12),
  .v82de4f(w14)
 );
 vad119b v3599be (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v0ef266(w11),
  .v27dec4(w16),
  .v82de4f(w19)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderC-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderC-4bits: Adder of two operands of 4 bits and Carry in
/*-------------------------------------------------*/
//---- Top entity
module vc3c498 (
 input [7:0] v45c6ee,
 input [7:0] v20212e,
 input vb9cfc3,
 output v4642b6,
 output [7:0] veeaa8e
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 wire [0:3] w11;
 assign w1 = vb9cfc3;
 assign w2 = v45c6ee;
 assign w3 = v20212e;
 assign veeaa8e = w4;
 assign v4642b6 = w7;
 v6bdcd9 v8d795a (
  .vcc8c7c(w3),
  .v651522(w10),
  .v2cc41f(w11)
 );
 v6bdcd9 v23dbc5 (
  .vcc8c7c(w2),
  .v651522(w8),
  .v2cc41f(w9)
 );
 vafb28f vef3a58 (
  .va9ac17(w4),
  .v3c88fc(w5),
  .v515fe7(w6)
 );
 va1ce30 v0ff71a (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .v817794(w5),
  .v0550b6(w9),
  .v24708e(w11)
 );
 va1ce30 v12f94f (
  .vb9cfc3(w0),
  .v817794(w6),
  .v4642b6(w7),
  .v0550b6(w8),
  .v24708e(w10)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderC-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderC-8bits: Adder of two operands of 8 bits and Carry in
/*-------------------------------------------------*/
//---- Top entity
module v8cc49c (
 input [7:0] vb334ae,
 input [7:0] v2b8a97,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v14a530 = w0;
 assign w1 = v2b8a97;
 assign w2 = vb334ae;
 v8cc49c_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus16-Join-half  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus16-Join-half: Join the two same halves into an 16-bits Bus
/*-------------------------------------------------*/

module v8cc49c_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v332488 (
 input ved8395,
 input ve78ab8,
 output v3487af
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = ve78ab8;
 assign w1 = ved8395;
 assign v3487af = w2;
 assign w4 = ve78ab8;
 assign w4 = w0;
 vd12401 v456da5 (
  .vcbab45(w2),
  .v0e28cb(w3),
  .v3ca442(w4)
 );
 v053dc2 vdfab80 (
  .vf54559(w0),
  .va4102a(w1),
  .ve8318d(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Edges-detector  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Edges detector. It generates a 1-period pulse (tic) when either a rising edge or a falling edge is detected on the input
/*-------------------------------------------------*/
//---- Top entity
module vdc93d6 (
 input v717e81,
 input ve7f5e6,
 output v3c12b5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = ve7f5e6;
 assign v3c12b5 = w2;
 assign w3 = v717e81;
 assign w4 = v717e81;
 assign w4 = w3;
 v053dc2 vbb75a1 (
  .vf54559(w0),
  .ve8318d(w1),
  .va4102a(w4)
 );
 v053dc2 vf6c433 (
  .vf54559(w1),
  .ve8318d(w2),
  .va4102a(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sync-x01  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sync 1-bit input with the system clock domain
/*-------------------------------------------------*/
//---- Top entity
module vad96dc #(
 parameter v6a9fe4 = 0
) (
 input v27dec4,
 output v4642b6
);
 localparam p0 = v6a9fe4;
 wire w1;
 wire w2;
 wire w3;
 assign w2 = v27dec4;
 assign v4642b6 = w3;
 vd12401 v5b01c7 (
  .v0e28cb(w1),
  .v3ca442(w2),
  .vcbab45(w3)
 );
 v6b14d5 #(
  .vc5c8ea(p0)
 ) v94e17e (
  .v268bfc(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- not-wire-x01  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Select positive or negative logic for the input (0=positive, 1=negative)
/*-------------------------------------------------*/
//---- Top entity
module v6b14d5 #(
 parameter vc5c8ea = 0
) (
 output v268bfc
);
 localparam p0 = vc5c8ea;
 wire w1;
 assign v268bfc = w1;
 v6b14d5_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1-bit-gen-constant  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 1-bit generic constant (0/1)
/*-------------------------------------------------*/

module v6b14d5_v465065 #(
 parameter VALUE = 0
) (
 output k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v95d0ae #(
 parameter vc5c8ea = 0
) (
 output [19:0] v2531bd
);
 localparam p0 = vc5c8ea;
 wire [0:19] w1;
 assign v2531bd = w1;
 v95d0ae_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 20-bits-gen-constant  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Generic: 20-bits generic constant
/*-------------------------------------------------*/

module v95d0ae_v465065 #(
 parameter VALUE = 0
) (
 output [19:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vbe214f (
 input [19:0] v2c450d,
 input [19:0] va1de2f,
 input v2d3366,
 output [19:0] v3f443e
);
 wire [0:19] w0;
 wire [0:19] w1;
 wire [0:19] w2;
 wire [0:3] w3;
 wire [0:7] w4;
 wire [0:7] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire [0:7] w11;
 wire [0:7] w12;
 wire [0:7] w13;
 wire [0:7] w14;
 assign w0 = va1de2f;
 assign w1 = v2c450d;
 assign v3f443e = w2;
 assign w8 = v2d3366;
 assign w9 = v2d3366;
 assign w10 = v2d3366;
 assign w9 = w8;
 assign w10 = w8;
 assign w10 = w9;
 v1bbb5b v41cfb0 (
  .v9d2a6a(w5),
  .v2d3366(w10),
  .v2a1cbe(w13),
  .v9d7ae8(w14)
 );
 v1bbb5b vf7893e (
  .v9d2a6a(w4),
  .v2d3366(w9),
  .v2a1cbe(w11),
  .v9d7ae8(w12)
 );
 v2dbbdf v65d85e (
  .v0bc190(w0),
  .v906d8f(w7),
  .v89b162(w12),
  .ve1a6e8(w14)
 );
 v2dbbdf vac3ded (
  .v0bc190(w1),
  .v906d8f(w6),
  .v89b162(w11),
  .ve1a6e8(w13)
 );
 v952eda v984575 (
  .v6833fd(w3),
  .v54ac99(w6),
  .ve2616d(w7),
  .v2d3366(w8)
 );
 ve697e9 v765ab3 (
  .v2e2bd0(w2),
  .v55cd06(w3),
  .v2e94db(w4),
  .v43dfba(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- 20-bits-Mux-2-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 2-to-1 Multplexer (20-bit channels)
/*-------------------------------------------------*/
//---- Top entity
module v1bbb5b (
 input [7:0] v2a1cbe,
 input [7:0] v9d7ae8,
 input v2d3366,
 output [7:0] v9d2a6a
);
 wire [0:3] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire [0:3] w10;
 assign v9d2a6a = w1;
 assign w2 = v2a1cbe;
 assign w3 = v9d7ae8;
 assign w8 = v2d3366;
 assign w9 = v2d3366;
 assign w9 = w8;
 v952eda v54aed2 (
  .v6833fd(w0),
  .v54ac99(w7),
  .v2d3366(w9),
  .ve2616d(w10)
 );
 vafb28f v117a88 (
  .v3c88fc(w0),
  .va9ac17(w1),
  .v515fe7(w4)
 );
 v6bdcd9 v9f32ae (
  .vcc8c7c(w2),
  .v651522(w5),
  .v2cc41f(w7)
 );
 v6bdcd9 v9881c7 (
  .vcc8c7c(w3),
  .v651522(w6),
  .v2cc41f(w10)
 );
 v952eda v34a43a (
  .v6833fd(w4),
  .v54ac99(w5),
  .ve2616d(w6),
  .v2d3366(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- 8-bits-Mux-2-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 2-to-1 Multplexer (8-bit channels)
/*-------------------------------------------------*/
//---- Top entity
module v952eda (
 input [3:0] v54ac99,
 input [3:0] ve2616d,
 input v2d3366,
 output [3:0] v6833fd
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:3] w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign v6833fd = w3;
 assign w5 = ve2616d;
 assign w6 = v54ac99;
 assign w9 = v2d3366;
 assign w10 = v2d3366;
 assign w11 = v2d3366;
 assign w12 = v2d3366;
 assign w10 = w9;
 assign w11 = w9;
 assign w11 = w10;
 assign w12 = w9;
 assign w12 = w10;
 assign w12 = w11;
 vd0c4e5 v6d94c9 (
  .v030ad0(w0),
  .v2d3366(w11),
  .v27dec4(w15),
  .vb192d0(w17)
 );
 vd0c4e5 vebe465 (
  .v030ad0(w1),
  .v2d3366(w12),
  .v27dec4(w16),
  .vb192d0(w18)
 );
 vd0c4e5 ve1c21f (
  .v030ad0(w2),
  .v2d3366(w10),
  .v27dec4(w13),
  .vb192d0(w14)
 );
 v84f0a1 va44bdf (
  .vee8a83(w0),
  .v03aaf0(w1),
  .vf8041d(w2),
  .v11bca5(w3),
  .vd84a57(w4)
 );
 vd0c4e5 v2ebff3 (
  .v030ad0(w4),
  .v27dec4(w7),
  .vb192d0(w8),
  .v2d3366(w9)
 );
 vc4f23a v3c3a57 (
  .v985fcb(w5),
  .v4f1fd3(w8),
  .vda577d(w14),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a vd6d480 (
  .v985fcb(w6),
  .v4f1fd3(w7),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
endmodule

/*-------------------------------------------------*/
/*-- 4-bits-Mux-2-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 2-to-1 Multplexer (4-bit channels)
/*-------------------------------------------------*/
//---- Top entity
module vd0c4e5 (
 input v27dec4,
 input vb192d0,
 input v2d3366,
 output v030ad0
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign v030ad0 = w0;
 assign w2 = v2d3366;
 assign w3 = v2d3366;
 assign w6 = v27dec4;
 assign w7 = vb192d0;
 assign w3 = w2;
 v873425 vaaee1f (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w4)
 );
 vba518e v569873 (
  .vcbab45(w1),
  .v3ca442(w2),
  .v0e28cb(w6)
 );
 v3676a0 v1f00ae (
  .v0e28cb(w3),
  .vcbab45(w5)
 );
 vba518e vc8527f (
  .vcbab45(w4),
  .v3ca442(w5),
  .v0e28cb(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux-2-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 2-to-1 Multplexer (1-bit channels)
/*-------------------------------------------------*/
//---- Top entity
module v2dbbdf (
 input [19:0] v0bc190,
 output [3:0] v906d8f,
 output [7:0] v89b162,
 output [7:0] ve1a6e8
);
 wire [0:19] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:3] w3;
 assign w0 = v0bc190;
 assign ve1a6e8 = w1;
 assign v89b162 = w2;
 assign v906d8f = w3;
 v2dbbdf_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus20-Split-4-8-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus20-Split-4-8-8: Split the 20-bits bus into three buses of 4, 8 and 8 wires
/*-------------------------------------------------*/

module v2dbbdf_v9a2a06 (
 input [19:0] i,
 output [3:0] o2,
 output [7:0] o1,
 output [7:0] o0
);
 assign o2 = i[19:16];
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module ve697e9 (
 input [3:0] v55cd06,
 input [7:0] v2e94db,
 input [7:0] v43dfba,
 output [19:0] v2e2bd0
);
 wire [0:19] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign v2e2bd0 = w0;
 assign w1 = v55cd06;
 assign w2 = v2e94db;
 assign w3 = v43dfba;
 ve697e9_v9a2a06 v9a2a06 (
  .o(w0),
  .i2(w1),
  .i1(w2),
  .i0(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus20-Join-4-8-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus20-Join-4-8-8: Join the three buses into an 20-bits Bus
/*-------------------------------------------------*/

module ve697e9_v9a2a06 (
 input [3:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 output [19:0] o
);
 assign o = {i2, i1, i0};
 
endmodule
//---- Top entity
module v82aaa0 (
 input v6dda25,
 input [19:0] vb2cfec,
 output [19:0] vb319d4,
 output ve37344
);
 wire [0:19] w0;
 wire w1;
 wire [0:19] w2;
 wire [0:19] w3;
 wire w4;
 wire w5;
 assign w1 = v6dda25;
 assign vb319d4 = w2;
 assign w3 = vb2cfec;
 assign ve37344 = w4;
 assign w2 = w0;
 assign w5 = w4;
 v2d3c65 v55c934 (
  .v545b15(w0),
  .v6dda25(w1),
  .ve556f1(w5)
 );
 vb9ddd5 v90643f (
  .v07eb94(w0),
  .vdb40a4(w3),
  .v4642b6(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- syscounter-M-20bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- syscounter-M-20-bits: 2-bits Module M Syscounter
/*-------------------------------------------------*/
//---- Top entity
module v2d3c65 (
 input v6dda25,
 input ve556f1,
 output [19:0] v545b15,
 output ve37344
);
 wire w0;
 wire [0:19] w1;
 wire [0:19] w2;
 wire w3;
 wire [0:19] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v545b15 = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 v8c6884 vfba29e (
  .v782748(w0),
  .v1be022(w1),
  .vf06540(w2),
  .v6dda25(w3)
 );
 vd98b4e v91c0a7 (
  .v4ad898(w1),
  .vd1d627(w2),
  .v4642b6(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- syscounter-rst-16bits CLONE  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 16-bits Syscounter with reset
/*-------------------------------------------------*/
//---- Top entity
module v8c6884 (
 input v6dda25,
 input v782748,
 input [19:0] vf06540,
 output [19:0] v1be022
);
 wire [0:19] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 wire [0:19] w3;
 wire [0:3] w4;
 wire [0:15] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign w0 = vf06540;
 assign v1be022 = w3;
 assign w6 = v6dda25;
 assign w7 = v6dda25;
 assign w8 = v782748;
 assign w9 = v782748;
 assign w7 = w6;
 assign w9 = w8;
 v5c75f6 v9f7443 (
  .v4de61b(w2),
  .v50034e(w4),
  .v6dda25(w6),
  .v782748(w8)
 );
 vafdfd8 vae4b72 (
  .v0bc190(w0),
  .vb68a0b(w1),
  .vd8e8a3(w2)
 );
 vbc711b v5796e0 (
  .vc320da(w1),
  .v3f90b8(w5),
  .v6dda25(w7),
  .v782748(w9)
 );
 vdecca3 v0ddafc (
  .v2e2bd0(w3),
  .v55cd06(w4),
  .vbf8961(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- DFF-rst-x20  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- DFF-rst-x20: 20 D flip-flops in paralell with reset
/*-------------------------------------------------*/
//---- Top entity
module vafdfd8 (
 input [19:0] v0bc190,
 output [3:0] vd8e8a3,
 output [15:0] vb68a0b
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:19] w2;
 assign vb68a0b = w0;
 assign vd8e8a3 = w1;
 assign w2 = v0bc190;
 vafdfd8_v9a2a06 v9a2a06 (
  .o0(w0),
  .o1(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus20-Split-4-16  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus20-Split-4-16: Split the 20-bits bus into two buses of 4 and 16 wires
/*-------------------------------------------------*/

module vafdfd8_v9a2a06 (
 input [19:0] i,
 output [3:0] o1,
 output [15:0] o0
);
 assign o1 = i[19:16];
 assign o0 = i[15:0];
endmodule
//---- Top entity
module vdecca3 (
 input [3:0] v55cd06,
 input [15:0] vbf8961,
 output [19:0] v2e2bd0
);
 wire [0:19] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 assign v2e2bd0 = w0;
 assign w1 = vbf8961;
 assign w2 = v55cd06;
 vdecca3_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus20-Join-4-16  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus20-Join-half: Join the two buses into an 20-bits Bus
/*-------------------------------------------------*/

module vdecca3_v9a2a06 (
 input [3:0] i1,
 input [15:0] i0,
 output [19:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vd98b4e #(
 parameter v6c5139 = 1
) (
 input [19:0] v4ad898,
 output v4642b6,
 output [19:0] vd1d627
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:19] w2;
 wire [0:19] w3;
 assign v4642b6 = w0;
 assign w2 = v4ad898;
 assign vd1d627 = w3;
 vf09b6a #(
  .vd73390(p1)
 ) v13dd2b (
  .v4642b6(w0),
  .vf0a425(w2),
  .va63e91(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Inc1-20bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Inc1-20bit: Increment a 20-bits number by one
/*-------------------------------------------------*/
//---- Top entity
module vf09b6a #(
 parameter vd73390 = 0
) (
 input [19:0] vf0a425,
 output v4642b6,
 output [19:0] va63e91
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:19] w2;
 wire [0:19] w3;
 wire [0:19] w4;
 assign v4642b6 = w0;
 assign w3 = vf0a425;
 assign va63e91 = w4;
 v4e3dc9 vb19a98 (
  .v4642b6(w0),
  .ve4715b(w2),
  .v4895ee(w3),
  .vd66696(w4)
 );
 v95d0ae #(
  .vc5c8ea(p1)
 ) v1ff9a2 (
  .v2531bd(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AdderK-16bits CLONE  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AdderK-16bit: Adder of 16-bit operand and 16-bit constant
/*-------------------------------------------------*/
//---- Top entity
module v4e3dc9 (
 input [19:0] ve4715b,
 input [19:0] v4895ee,
 output v4642b6,
 output [19:0] vd66696
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:11] w3;
 wire [0:19] w4;
 wire [0:19] w5;
 wire [0:11] w6;
 wire w7;
 wire w8;
 wire [0:3] w9;
 wire [0:15] w10;
 wire [0:19] w11;
 wire [0:3] w12;
 wire [0:3] w13;
 wire [0:7] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:7] w17;
 assign w4 = v4895ee;
 assign w5 = ve4715b;
 assign v4642b6 = w8;
 assign vd66696 = w11;
 vcb23aa v8e0bba (
  .v4642b6(w0),
  .v62bf25(w2),
  .v39966a(w16),
  .veb2f59(w17)
 );
 vc3c498 v917bbf (
  .vb9cfc3(w0),
  .veeaa8e(w1),
  .v4642b6(w7),
  .v45c6ee(w14),
  .v20212e(w15)
 );
 v8cc49c v03c3e3 (
  .vb334ae(w1),
  .v2b8a97(w2),
  .v14a530(w10)
 );
 v0f6c39 v672b5a (
  .vb09d88(w3),
  .v0bc190(w4),
  .ve1a6e8(w17)
 );
 vc97ea6 v91419d (
  .v1215c2(w3),
  .v51ed6c(w13),
  .vc673c0(w15)
 );
 v0f6c39 vc7e44e (
  .v0bc190(w5),
  .vb09d88(w6),
  .ve1a6e8(w16)
 );
 vc97ea6 vda03c3 (
  .v1215c2(w6),
  .v51ed6c(w12),
  .vc673c0(w14)
 );
 va1ce30 v32065a (
  .vb9cfc3(w7),
  .v4642b6(w8),
  .v817794(w9),
  .v0550b6(w12),
  .v24708e(w13)
 );
 vdecca3 v23cb4f (
  .v55cd06(w9),
  .vbf8961(w10),
  .v2e2bd0(w11)
 );
endmodule

/*-------------------------------------------------*/
/*-- Adder-20bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Adder-20bits: Adder of two operands of 20 bits
/*-------------------------------------------------*/
//---- Top entity
module v0f6c39 (
 input [19:0] v0bc190,
 output [11:0] vb09d88,
 output [7:0] ve1a6e8
);
 wire [0:19] w0;
 wire [0:7] w1;
 wire [0:11] w2;
 assign w0 = v0bc190;
 assign ve1a6e8 = w1;
 assign vb09d88 = w2;
 v0f6c39_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus20-Split-12-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus20-Split-8-12: Split the 20-bits bus into two buses of 8 and 12 wires
/*-------------------------------------------------*/

module v0f6c39_v9a2a06 (
 input [19:0] i,
 output [11:0] o1,
 output [7:0] o0
);
 assign o1 = i[19:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vc97ea6 (
 input [11:0] v1215c2,
 output [3:0] v51ed6c,
 output [7:0] vc673c0
);
 wire [0:3] w0;
 wire [0:11] w1;
 wire [0:7] w2;
 assign v51ed6c = w0;
 assign w1 = v1215c2;
 assign vc673c0 = w2;
 vc97ea6_v9a2a06 v9a2a06 (
  .o1(w0),
  .i(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Bus12-Split-4-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Bus12-Split-4-8: Split the 12-bits bus into two buses of 4 and 8 wires
/*-------------------------------------------------*/

module vc97ea6_v9a2a06 (
 input [11:0] i,
 output [3:0] o1,
 output [7:0] o0
);
 
 assign o1 = i[11:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vb9ddd5 (
 input [19:0] vdb40a4,
 input [19:0] v07eb94,
 output v4642b6
);
 wire w0;
 wire [0:19] w1;
 wire [0:19] w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:3] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 assign v4642b6 = w0;
 assign w1 = v07eb94;
 assign w2 = vdb40a4;
 vb2762a vb6832a (
  .v4642b6(w3),
  .v715730(w8),
  .vf191e6(w11)
 );
 vb2762a v302658 (
  .v4642b6(w4),
  .v715730(w7),
  .vf191e6(w10)
 );
 v2dbbdf vb63230 (
  .v0bc190(w1),
  .v906d8f(w9),
  .v89b162(w10),
  .ve1a6e8(w11)
 );
 v2dbbdf veb4dc0 (
  .v0bc190(w2),
  .v906d8f(w6),
  .v89b162(w7),
  .ve1a6e8(w8)
 );
 v438230 vc72070 (
  .v4642b6(w5),
  .v693354(w6),
  .v5369cd(w9)
 );
 vae245c v9196c7 (
  .vcbab45(w0),
  .v3ca442(w3),
  .v0e28cb(w4),
  .v033bf6(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-20bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-20bit: Comparator of two 20-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module vb2762a (
 input [7:0] v715730,
 input [7:0] vf191e6,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 assign v4642b6 = w0;
 assign w3 = v715730;
 assign w4 = vf191e6;
 v438230 v577a36 (
  .v4642b6(w2),
  .v693354(w6),
  .v5369cd(w8)
 );
 vba518e v707c6e (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 v6bdcd9 v921a9f (
  .vcc8c7c(w4),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v6bdcd9 v8cfa4d (
  .vcc8c7c(w3),
  .v651522(w5),
  .v2cc41f(w6)
 );
 v438230 vfc1765 (
  .v4642b6(w1),
  .v693354(w5),
  .v5369cd(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-8bit: Comparator of two 8-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module v438230 (
 input [3:0] v693354,
 input [3:0] v5369cd,
 output v4642b6
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 assign v4642b6 = w0;
 assign w1 = v693354;
 assign w2 = v5369cd;
 v23b15b v09a5a5 (
  .v4642b6(w3),
  .v27dec4(w12),
  .v6848e9(w14)
 );
 v23b15b vc1b29d (
  .v4642b6(w4),
  .v27dec4(w11),
  .v6848e9(w13)
 );
 v23b15b vcd27ce (
  .v4642b6(w5),
  .v27dec4(w9),
  .v6848e9(w10)
 );
 vc4f23a vea9c80 (
  .v985fcb(w1),
  .v4f1fd3(w7),
  .vda577d(w9),
  .v3f8943(w11),
  .v64d863(w12)
 );
 vc4f23a va7dcdc (
  .v985fcb(w2),
  .v4f1fd3(w8),
  .vda577d(w10),
  .v3f8943(w13),
  .v64d863(w14)
 );
 v23b15b va0849c (
  .v4642b6(w6),
  .v27dec4(w7),
  .v6848e9(w8)
 );
 veffd42 v6e3e65 (
  .vcbab45(w0),
  .v3ca442(w3),
  .v0e28cb(w4),
  .v033bf6(w5),
  .v9eb652(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-4bit: Comparator of two 4-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module v23b15b (
 input v27dec4,
 input v6848e9,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w1 = v27dec4;
 assign v4642b6 = w2;
 assign w3 = v6848e9;
 vd12401 v955b2b (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v3676a0 vf92936 (
  .v0e28cb(w0),
  .vcbab45(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-1bit: Comparator of two 1-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module veffd42 (
 input v9eb652,
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = v3ca442;
 assign w1 = v9eb652;
 assign w2 = v033bf6;
 assign w3 = v0e28cb;
 assign vcbab45 = w4;
 vba518e vf3ef0f (
  .v3ca442(w0),
  .v0e28cb(w3),
  .vcbab45(w6)
 );
 vba518e vdcc53d (
  .v0e28cb(w1),
  .v3ca442(w2),
  .vcbab45(w5)
 );
 vba518e v17ac22 (
  .vcbab45(w4),
  .v0e28cb(w5),
  .v3ca442(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND4  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Three bits input And gate
/*-------------------------------------------------*/
//---- Top entity
module vae245c (
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v033bf6;
 assign w1 = v0e28cb;
 assign w2 = v3ca442;
 assign vcbab45 = w4;
 vba518e v19b5b0 (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w3)
 );
 vba518e vf3ef0f (
  .v3ca442(w2),
  .v0e28cb(w3),
  .vcbab45(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND3  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Three bits input And gate
/*-------------------------------------------------*/
//---- Top entity
module v1bc657 (
 input [19:0] v0e4f6c,
 input [19:0] v0a4fd8,
 output v4642b6
);
 wire [0:19] w0;
 wire [0:19] w1;
 wire w2;
 assign w0 = v0e4f6c;
 assign w1 = v0a4fd8;
 assign v4642b6 = w2;
 v1bc657_v863693 v863693 (
  .a(w0),
  .b(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- less-eq-20bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Less-eq-20bit: Comparator of two 20-bit numbers
/*-------------------------------------------------*/

module v1bc657_v863693 (
 input [19:0] a,
 input [19:0] b,
 output o
);
 assign o = (a <= b);
endmodule
//---- Top entity
module v58b797 (
 input v6dda25,
 input [15:0] v2dc030,
 output [15:0] v551ad3,
 output ve37344
);
 wire [0:15] w0;
 wire w1;
 wire [0:15] w2;
 wire [0:15] w3;
 wire w4;
 wire w5;
 assign w1 = v6dda25;
 assign v551ad3 = w2;
 assign w3 = v2dc030;
 assign ve37344 = w4;
 assign w2 = w0;
 assign w5 = w4;
 v413e4a v52120f (
  .v49911e(w0),
  .v6dda25(w1),
  .ve556f1(w5)
 );
 v3556c3 vc9e25f (
  .v6d9caf(w0),
  .veb1f69(w3),
  .v4642b6(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- syscounter-M-16bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- syscounter-M-16-bits: 16-bits Module M Syscounter
/*-------------------------------------------------*/
//---- Top entity
module v3556c3 (
 input [15:0] veb1f69,
 input [15:0] v6d9caf,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:15] w3;
 wire [0:15] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 assign v4642b6 = w0;
 assign w3 = veb1f69;
 assign w4 = v6d9caf;
 vba518e v707c6e (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 vb2762a vb6832a (
  .v4642b6(w2),
  .v715730(w6),
  .vf191e6(w8)
 );
 v306ca3 v357be1 (
  .v91b9c1(w4),
  .vef5eee(w7),
  .vd3ef3b(w8)
 );
 v306ca3 v713b54 (
  .v91b9c1(w3),
  .vef5eee(w5),
  .vd3ef3b(w6)
 );
 vb2762a v302658 (
  .v4642b6(w1),
  .v715730(w5),
  .vf191e6(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- comp2-16bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comp2-16bit: Comparator of two 16-bit numbers
/*-------------------------------------------------*/
//---- Top entity
module vbef3fc #(
 parameter v8bcde4 = 0
) (
 input v6dda25,
 input v3dc29f,
 output v4642b6
);
 localparam p1 = v8bcde4;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w2 = v3dc29f;
 assign w3 = v6dda25;
 assign v4642b6 = w4;
 assign w5 = w4;
 v3676a0 vdebd76 (
  .vcbab45(w0),
  .v0e28cb(w5)
 );
 v22cb98 #(
  .v5462c0(p1)
 ) v51de32 (
  .v27dec4(w0),
  .vd793aa(w2),
  .ve4a668(w3),
  .v4642b6(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Counter-x01  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Counter-x01: 1-bit counter
/*-------------------------------------------------*/
//---- Top entity
module v22cb98 #(
 parameter v5462c0 = 0
) (
 input ve4a668,
 input v27dec4,
 input vd793aa,
 output v4642b6
);
 localparam p1 = v5462c0;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w2 = ve4a668;
 assign w3 = v27dec4;
 assign v4642b6 = w5;
 assign w6 = vd793aa;
 assign w5 = w4;
 va40d2f v9ff767 (
  .v030ad0(w0),
  .vb192d0(w3),
  .v27dec4(w4),
  .v2d3366(w6)
 );
 v053dc2 #(
  .v71e305(p1)
 ) v89c757 (
  .vf54559(w0),
  .va4102a(w2),
  .ve8318d(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1-bit-reg  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Reg: 1-Bit register
/*-------------------------------------------------*/
//---- Top entity
module va40d2f (
 input v27dec4,
 input vb192d0,
 input v2d3366,
 output v030ad0
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v030ad0 = w0;
 assign w1 = v2d3366;
 assign w2 = v27dec4;
 assign w3 = vb192d0;
 vd0c4e5 v0f3fef (
  .v030ad0(w0),
  .v2d3366(w1),
  .vb192d0(w2),
  .v27dec4(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- MuxF-2-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 2-to-1 Multplexer (1-bit channels). Fippled version
/*-------------------------------------------------*/
//---- Top entity
module v7ebc90 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v7ebc90_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AND logic gate
/*-------------------------------------------------*/

module v7ebc90_vf4938a (
 input a,
 input b,
 output c
);
 // AND logic gate
 
 assign c = a & b;
endmodule
//---- Top entity
module v528969 (
 input v483980,
 input vb7d864,
 output vb5d757
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vb7d864;
 assign w1 = v483980;
 assign vb5d757 = w2;
 v528969_vf4938a vf4938a (
  .b(w0),
  .a(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR logic gate
/*-------------------------------------------------*/

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
